baseURL = 'https://cv.berkantgultekin.com'
languageCode = 'en-us'
title = 'CV | Berkant Gültekin'
disableKinds = ["taxonomy", "term"]

defaultContentLanguage = 'en'
[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    [languages.en.params]
      datasource = 'content.en'
  [languages.de]
    languageName = "Deutsch"
    weight = 2
    [languages.de.params]
      datasource = 'content.de'
